### ISSUE TITLE
Untracked files

### ISSUE THREAD

**Issue by rafid-mahdi** [DT142G-Project-2015/android-app#2]
I read https://www.kernel.org/pub/software/scm/git/docs/git-update-index.html and tried:
git update-index --assume-unchanged .idea/

tell me if you still get untracked files when doing 
1. git pull
2. opening android studio
3. git status

**Comment by joeledstrom** [comment]
This seems to be fixed for me by deleting all traces of the app on my computer then doing a fresh pull of the project, and re-importing it into Android Studio.

I just made a commit as well, and everything seems to work fine. No traces of .idea in the commit.

**Comment by antonflodin93** [comment]
Det funkade när jag committa också! Great jaaaaab :)

---- Joel Edström skrev ----

**Comment by joeledstrom** [comment]
Fixed.

**Comment by rafid-mahdi** [comment]
well if you recreate your entire local rep, of course it is going to work. the reason I tried this command was to check whether it would solve it for everyone who already is tracking the files. but I tested it myself and while it works for me, it only appears to modify the index file in the .git folder (which is local, not shared). so basically it doesnt do what I wanted it to do.

but do you really have to recreate your rep @joeledstrom ?  the way I understand it is:
- if you do a fresh pull (your first pull) of the rep with updated .gitignore, you shouldn't have a problem.  
- if you already are tracking files that you want to ignore, you need to manually remove the cache in your local .git folder for gitignore to work.

to anyone that still gets a notice about modifications to the .idea/ path, do this:

commit any changes you done, then do

git rm -r --cached .

git add .

If that doesn't work, you can do git update-index --assume-unchanged .idea/
or recreate your rep like Joel said.

**Comment by joeledstrom** [comment]
Yeah I guess you're right

If you have any local uncommited changes recreating it might be a bit harder than to use those commands.

I suppose we should leave this issue open for a while longer.
