### ISSUE TITLE
hur appen ska kommunicera med andra instanser av appen

### ISSUE THREAD

**Issue by rafid-mahdi** [DT142G-Project-2015/android-app#3]
har ni en lösning till hur kockens instans av appen ska kommunicera med servitörens instans av appen? om det inte går att få det fungera genom web-appen kan jag testa sockets; en server socket för kocken och client sockets för serviöterna. log in rutan identifierar vilken sockets som skapas. klienten lyssnar på servern, när klienten får ett meddelande från servern händer popup. 

om inte ni har en annan lösning förstås

**Comment by antonflodin93** [comment]
Borde det inte finnas nåt event som lyssnar efter förändringar i databasen och om så är fallet skriver ut dom? När ska du på skolan idag?

---- Rafid M skrev ----

**Comment by joeledstrom** [comment]
Genom servern kommer funka bra. Vi skulle ju kunna bara refresha var 5:e sekund eller liknande i prototypen.

Senare om vill förbättra och lägga till Push notiser, så kan man fixa [GCM](https://developers.google.com/cloud-messaging/)

**Comment by joeledstrom** [comment]
I första lösningen utan GCM tänkte jag att man startar en Service i kockens android app, som uppdaterar URL:en /api/orders?status=readyForKitchen med jämna mellanrum.

Om något uppdateras så kan man slänga upp en lokal notis med ljud/vibration osv.

Med tanke på att kocken kanske har sin tablet på laddning hela tiden, så kanske GCM är onödigt också. Största fördelen med GCM är väl att det sparar massvis med batteri.

**Comment by rafid-mahdi** [comment]
behöver det inte vara tvärtom? alltså att, när kocken markerar att något i köket är klart, skickas det till servern. därifrån kollar klienterna status, och om den tar emot rätt sak ges en notis. (?)

för vid något tillfälle behöver servitörerna hämta något för att göra en popup.

**Comment by sp1ndl3r** [comment]
Alltså när kocken är klar och swipar bort ett Item så ändras väl "order?status=readyForKitchen" till done. Om man då "refreshar" på klienterna var 5:e sekund borde man kunna koppla det till en notis eller något om den har ändrats i databasen? (Borde även kunna kolla vilken använder som lagt beställningen så att endast denne person får en notis)

**Comment by rafid-mahdi** [comment]
japp, sådär jag tänkte mig att det ska funka.

**Comment by joeledstrom** [comment]
Ja det är sant. Vi borde kanske koppla order till accunt också.
