### ISSUE TITLE
Lägga till Swipefunktionen i kitchenview igen

### ISSUE THREAD

**Issue by antonflodin93** [DT142G-Project-2015/android-app#5]
Funktionerna som "overridas" av SwipeListViewActivity i KitchenViewActivity måste implementeras nu när databaskopplingen fungerar.

**Comment by sp1ndl3r** [comment]
Hänger inte med, menar du att vi ska fixa så att man kan swipa bort dom?

**Comment by antonflodin93** [comment]
Precis! Just nu har vi ju bara kommentera bort koden som extendar ListViewActivityklassen. Det görs snabbt, men har felaktig kod just nu så fixar det imorrn istället.

**Comment by sp1ndl3r** [comment]
Måste även fylla på ApiInterface med "PUT" funktionen för att kunna ändra status.

**Comment by antonflodin93** [comment]
Lägg in det som en issue, eller?

**Comment by sp1ndl3r** [comment]
Nja menade att när man swipar ska den inte tas bort utan bara ändra status.

**Comment by antonflodin93** [comment]
Jaha, ja justeja så var det ja!
